ALTER TABLE "backlog"
  ADD COLUMN IF NOT EXISTS "task_type" VARCHAR(32),
  ADD COLUMN IF NOT EXISTS "modules" VARCHAR(64),
  ADD COLUMN IF NOT EXISTS "components" VARCHAR(128),
  ADD COLUMN IF NOT EXISTS "complexity" SMALLINT,
  ADD COLUMN IF NOT EXISTS "prompt_model" VARCHAR(255),
  ADD COLUMN IF NOT EXISTS "prompt_created_at" TIMESTAMPTZ(6),
  ADD COLUMN IF NOT EXISTS "prompt_duration_sec" INTEGER,
  ADD COLUMN IF NOT EXISTS "prompt_log_id" VARCHAR(128);

